DROP DATABASE IF EXISTS kauppatietokanta;

CREATE DATABASE kauppatietokanta;

USE kauppatietokanta;

CREATE TABLE asiakas 
(asnro MEDIUMINT NOT NULL UNIQUE AUTO_INCREMENT,
etunimi CHAR(30) NOT NULL,
sukunimi CHAR(30) NOT NULL,
kayttajatunnus CHAR(30) NOT NULL UNIQUE,
salasana CHAR(255) NOT NULL,
lahiosoite CHAR(50) NOT NULL,
postinumero TEXT NOT NULL,
postitoimipaikka CHAR(30) NOT NULL,
tili_luotu DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
vaaria_salasanayrityksia TINYINT NOT NULL DEFAULT 0,
viimeinen_vaara_salasana DATETIME DEFAULT NULL,
PRIMARY KEY (asnro)
);

CREATE TABLE tuotteet
(tuotenumero MEDIUMINT UNIQUE NOT NULL AUTO_INCREMENT,
tuotenimi CHAR(70) NOT NULL,
valmistaja CHAR(70) NOT NULL,
hinta DECIMAL (7,2) NOT NULL,
alv TINYINT NOT NULL,
alennus FLOAT NOT NULL DEFAULT 0,
alealkaa DATETIME NULL DEFAULT NULL,
aleloppuu DATETIME NULL DEFAULT NULL,
kategoria CHAR(50) NOT NULL,
lyhytkuvaus TEXT(300),
tuotekuvaus TEXT,
varastossa SMALLINT NOT NULL,
myymalassa SMALLINT NOT NULL,
lisatty DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
myyntialkaa DATETIME NULL DEFAULT NULL,
vedettymyynnista DATETIME NULL DEFAULT NULL,
kuvat TEXT NULL DEFAULT NULL,
PRIMARY KEY (tuotenumero)
);

CREATE TABLE ostoskori
(id BIGINT NOT NULL UNIQUE AUTO_INCREMENT,
asnro MEDIUMINT NULL DEFAULT NULL,
tila TINYINT(1) NOT NULL DEFAULT 0,
# etunimi CHAR(30) NOT NULL,
# sukunimi CHAR(30) NOT NULL,
# lahiosoite CHAR(50) NOT NULL,
# postinumero MEDIUMINT(5) NOT NULL,
# postitoimipaikka CHAR(30) NOT NULL,
luontipaiva DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
lisatietoja TEXT NULL DEFAULT NULL,
PRIMARY KEY (id),
CONSTRAINT `fk_ostoskori_asiakas` FOREIGN KEY (`asnro`) REFERENCES `asiakas` (`asnro`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE ostoskorinesine 
(id BIGINT NOT NULL UNIQUE AUTO_INCREMENT,
tuotenumero MEDIUMINT NOT NULL,
ostoskorinid BIGINT NOT NULL,
hinta DECIMAL(8,2) NOT NULL DEFAULT 0,
alv TINYINT NOT NULL,
alennus FLOAT NOT NULL DEFAULT 0,
maara SMALLINT(6) NOT NULL DEFAULT 0,
luotu DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
PRIMARY KEY (id),
CONSTRAINT `fk_ostoskoriesine_tuotteet` FOREIGN KEY (`tuotenumero`) REFERENCES `tuotteet` (`tuotenumero`) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT `fk_ostoskoriesine_ostoskori` FOREIGN KEY (`ostoskorinid`) REFERENCES `ostoskori` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE tilaukset
(id MEDIUMINT NOT NULL UNIQUE AUTO_INCREMENT,
asnro MEDIUMINT NOT NULL,
tila TINYINT(1) NOT NULL DEFAULT 1,
kokonaishinta DECIMAL(8,2) NOT NULL DEFAULT 0,
toimituskulut DECIMAL(7,2) NOT NULL DEFAULT 0,
etunimi CHAR(30) NOT NULL,
sukunimi CHAR(30) NOT NULL,
lahiosoite CHAR(50) NOT NULL,
postinumero MEDIUMINT(5) NOT NULL,
postitoimipaikka CHAR(30) NOT NULL,
tilauspaivamaara DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
lisatietoja TEXT NULL DEFAULT NULL,
PRIMARY KEY (id),
CONSTRAINT `fk_tilaukset_asiakas` FOREIGN KEY (`asnro`) REFERENCES `asiakas` (`asnro`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE tilauksenesineet
(id BIGINT NOT NULL UNIQUE AUTO_INCREMENT,
tuotenumero MEDIUMINT UNIQUE NOT NULL,
tilausid MEDIUMINT NOT NULL,
hintatilaushetkella DECIMAL(8,2) NOT NULL DEFAULT 0,
alv TINYINT NOT NULL,
alennustilaushetkella FLOAT NOT NULL DEFAULT 0,
maara SMALLINT(6) NOT NULL DEFAULT 0,
tilauspvm DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
lisatietoja TEXT NULL DEFAULT NULL,
PRIMARY KEY (id),
CONSTRAINT `fk_tilauksenesineet_tuotteet` FOREIGN KEY (`tuotenumero`) REFERENCES `tuotteet` (`tuotenumero`) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT `fk_tilauksenesineet_tilaukset` FOREIGN KEY (`tilausid`) REFERENCES `tilaukset` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE transaktiot
(id BIGINT NOT NULL UNIQUE AUTO_INCREMENT,
asnro MEDIUMINT NOT NULL,
tilausid MEDIUMINT NOT NULL,
tyyppi TINYINT NOT NULL DEFAULT 0,
maksutapa TINYINT NOT NULL DEFAULT 0,
tila TINYINT NOT NULL DEFAULT 0,
luotu DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
lisatietoja TEXT NULL DEFAULT NULL,
PRIMARY KEY (id),
CONSTRAINT `fk_transaktiot_asiakas` FOREIGN KEY (`asnro`) REFERENCES `asiakas` (`asnro`) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT `fk_transaktiot_tilaukset` FOREIGN KEY (`tilausid`) REFERENCES `tilaukset` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE henkilokunta 
(id MEDIUMINT NOT NULL UNIQUE AUTO_INCREMENT,
etunimi CHAR(30) NOT NULL,
sukunimi CHAR(30) NOT NULL,
kayttajatunnus CHAR(30) NOT NULL UNIQUE,
tyyppi TINYINT NOT NULL DEFAULT 0,
salasana CHAR(255) NOT NULL,
lahiosoite CHAR(50) NOT NULL,
postinumero MEDIUMINT(5) NOT NULL,
postitoimipaikka CHAR(30) NOT NULL,
tili_luotu DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
vaaria_salasanayrityksia TINYINT NOT NULL DEFAULT 0,
viimeinen_vaara_salasana DATETIME DEFAULT NULL,
PRIMARY KEY (id)
);